### ISSUE TITLE
Windows: .\magpi-special-issue-downloader.ps1 is not working

### ISSUE THREAD

**Issue by somera** [joergi/MagPiDownloader#33] opened 2020-06-23 20:29 UTC
Beim .\magpi-special-issue-downloader.ps1 gibt es Fehler:

```
PS E:\MagPi\MagPiDownloader\windows> .\magpi-special-issue-downloader.ps1
Downloading Essentials_Games_v1.pdf
Ocorred an error trying download  +
Downloading Projects_Book_v1.pdf
Ocorred an error trying download  +
Downloading Projects_Book_v2.pdf
Ocorred an error trying download  +
Downloading Projects_Book_v3.pdf
Ocorred an error trying download  +
Downloading Essentials_Bash_v1.pdf
Ocorred an error trying download  +
Downloading Essentials_SenseHAT_v1.pdf
Ocorred an error trying download  +
Downloading Essentials_Sonic_Pi-v1.pdf
Ocorred an error trying download  +
Downloading Essentials_Scratch_v1.pdf
Ocorred an error trying download  +
Downloading Essentials_Minecraft_v1.pdf
Ocorred an error trying download  +
Downloading Essentials_GPIOZero_v1.pdf
Ocorred an error trying download  +
Downloading Essentials_C_v1.pdf
Ocorred an error trying download  +
Downloading Essentials_Camera_v1.pdf
Ocorred an error trying download  +
Downloading Essentials_AIY_Projects_Voice_v1.pdf
Ocorred an error trying download  +
Downloading Beginners_Book_v1.pdf
Ocorred an error trying download  +
Downloading Annual2018.pdf
Ocorred an error trying download  +
```

Die anderen Skripte klapten.

**Comment by joergi** [comment] 2020-06-24 06:20
@Rubemlrm -can you have a look? At least in the tests everything looks fine.
He says, that the special edition downloader makes problems, everything else is working.

**Comment by Rubemlrm** [comment] 2020-06-29 19:31
`# ------------------------------------------------------------------
# [Author] rubemlrm - https://github.com/joergi/MagPiDownloader
#          downloader for all MagPi issues
#          they are downloadable for free under https://www.raspberrypi.org/magpi/issues/
#          or you can buy the paper issues under: http://swag.raspberrypi.org/collections/magpi
#          this script is under GNU GENERAL PUBLIC LICENSE
# ------------------------------------------------------------------

# VERSION=0.1.0
# USAGE="Usage: ./magpi-special-issue-downloader.ps1"


# Check if directory dont exist and try create
if ( -Not (Test-Path -Path "special_issues" ) ) {
    New-Item -ItemType directory -Path "special_issues"
}

$special_issues = @(
    "Essentials_Games_v1.pdf",
    "Projects_Book_v1.pdf",
    "Projects_Book_v2.pdf",
    "Projects_Book_v3.pdf",
    "Essentials_Bash_v1.pdf",
    "Essentials_SenseHAT_v1.pdf",
    "Essentials_Sonic_Pi-v1.pdf",
    "Essentials_Scratch_v1.pdf",
    "Essentials_Minecraft_v1.pdf",
    "Essentials_GPIOZero_v1.pdf",
    "Essentials_C_v1.pdf",
    "Essentials_Camera_v1.pdf",
    "Essentials_AIY_Projects_Voice_v1.pdf",
    "Beginners_Book_v1.pdf",
    "Annual2018.pdf"
)

$baseUrl = "https://www.raspberrypi.org/magpi-issues"
$baseDir = (Split-Path -Path $PSScriptRoot -Parent)
$web = New-Object system.net.webclient
$errorCount = 0
foreach ($issue in $special_issues) {
    try {
        Write-Host Downloading $issue
        $fileUrl = $baseUrl + "/" + $issue
        $web.DownloadFile($fileUrl, "$baseDir\special_issues\$issue")
    }
    Catch {
        Write-Host $_.Exception | format-list -force
        Write-Host "Ocorred an error trying download " + $file
        $errorCount++
    }
}

if ($errorCount -gt 0) {
    exit 1
}`

@somera can you try run this script as debug? To check wich error is giving to you. On my 2 machines i can't reproduce that. This script have a line to throw a an exception with details to console.

**Comment by somera** [comment] 2020-07-05 20:22
> ```
> if ( -Not (Test-Path -Path "special_issues" ) ) {
>     New-Item -ItemType directory -Path "special_issues"
> }
> 
> $special_issues = @(
>     "Essentials_Games_v1.pdf",
>     "Projects_Book_v1.pdf",
>     "Projects_Book_v2.pdf",
>     "Projects_Book_v3.pdf",
>     "Essentials_Bash_v1.pdf",
>     "Essentials_SenseHAT_v1.pdf",
>     "Essentials_Sonic_Pi-v1.pdf",
>     "Essentials_Scratch_v1.pdf",
>     "Essentials_Minecraft_v1.pdf",
>     "Essentials_GPIOZero_v1.pdf",
>     "Essentials_C_v1.pdf",
>     "Essentials_Camera_v1.pdf",
>     "Essentials_AIY_Projects_Voice_v1.pdf",
>     "Beginners_Book_v1.pdf",
>     "Annual2018.pdf"
> )
> 
> $baseUrl = "https://www.raspberrypi.org/magpi-issues"
> $baseDir = (Split-Path -Path $PSScriptRoot -Parent)
> $web = New-Object system.net.webclient
> $errorCount = 0
> foreach ($issue in $special_issues) {
>     try {
>         Write-Host Downloading $issue
>         $fileUrl = $baseUrl + "/" + $issue
>         $web.DownloadFile($fileUrl, "$baseDir\special_issues\$issue")
>     }
>     Catch {
>         Write-Host $_.Exception | format-list -force
>         Write-Host "Ocorred an error trying download " + $file
>         $errorCount++
>     }
> }
> 
> if ($errorCount -gt 0) {
>     exit 1
> }
> ```
> 
> @somera can you try run this script as debug? To check wich error is giving to you. On my 2 machines i can't reproduce that. This script have a line to throw a an exception with details to console.

How to start the script with debug mode?

**Comment by joergi** [comment] 2020-07-10 00:00
@Rubemlrm

**Comment by Rubemlrm** [comment] 2020-07-11 10:36
@joergi @somera you just need to run the script `.\magpi-special-issue-downloader.ps1` the error it will be outputted into terminal during the runtime.

**Comment by somera** [comment] 2020-07-12 22:14
> @joergi @somera you just need to run the script `.\magpi-special-issue-downloader.ps1` the error it will be outputted into terminal during the runtime.

Nothing ...

```
PS E:\Raspberry Pi\MagPi\MagPiDownloader\windows> .\magpi-special-issue-downloader.ps1


    Verzeichnis: E:\Raspberry Pi\MagPi\MagPiDownloader\windows


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        13.07.2020     00:14                special_issues
```

I pulled the current master.

**Comment by Rubemlrm** [comment] 2020-07-13 07:55
@somera with the last version from Master branch it's all working fine?

**Comment by somera** [comment] 2020-07-13 08:15
> @somera with the last version from Master branch it's all working fine?

there was no error message. but no download too.

**Comment by joergi** [comment] 2020-07-13 21:57
@somera all other Windows scripts from this project work on your Windows machine? 
just not the this one?
that's really strange :-(

**Comment by Rubemlrm** [comment] 2020-07-13 22:17
@somera can you provide the windows version, powershell version? I'm trying to reproduce this behavior.

**Comment by somera** [comment] 2020-07-13 23:00
> @somera can you provide the windows version, powershell version? I'm trying to reproduce this behavior.

5.1.19041.1

**Comment by joergi** [comment] 2020-07-14 20:07
@somera -> https://github.com/joergi/MagPiDownloader/issues/33#issuecomment-657813844
?

**Comment by Rubemlrm** [comment] 2020-07-28 18:52
since there is no reply since 14/07 i think we can close this issue during this week. Maybe the problem was already solved.

**Comment by joergi** [comment] 2020-07-28 23:59
I agree @Rubemlrm 

@somera  - feel free to comment if you still have issues!

**Closed by joergi** 2020-07-28 23:59 UTC
Labels: Windows OS, bug, need more info
